/**
 * MTN MoMo Collections API Client
 * Handles token management, Request to Pay, and transaction status.
 *
 * Sandbox base: https://sandbox.momodeveloper.mtn.com
 * Production base: https://proxy.momoapi.mtn.com  (Zambia)
 *
 * Credentials stored in environment variables — never hardcoded.
 */

/* ── Configuration ─────────────────────────────────────────── */

interface MtnConfig {
  baseUrl: string;
  apiUserId: string;
  apiKey: string;
  subscriptionKey: string;
  targetEnvironment: string;
  currency: string;
  callbackUrl: string;
}

function getConfig(): MtnConfig {
  const isSandbox = process.env.MTN_MOMO_ENVIRONMENT !== "production";

  return {
    baseUrl: isSandbox
      ? "https://sandbox.momodeveloper.mtn.com"
      : "https://proxy.momoapi.mtn.com",
    apiUserId: process.env.MTN_MOMO_API_USER_ID!,
    apiKey: process.env.MTN_MOMO_API_KEY!,
    subscriptionKey: process.env.MTN_MOMO_SUBSCRIPTION_KEY!,
    targetEnvironment: isSandbox ? "sandbox" : "mtnzambia",
    currency: isSandbox ? "EUR" : "ZMW",
    callbackUrl:
      process.env.MTN_MOMO_CALLBACK_URL ||
      `${process.env.NEXT_PUBLIC_SITE_URL || "https://dmsuite-iota.vercel.app"}/api/payments/mtn/webhook`,
  };
}

/** Check if MTN MoMo is configured */
export function isMtnConfigured(): boolean {
  return !!(
    process.env.MTN_MOMO_API_USER_ID &&
    process.env.MTN_MOMO_API_KEY &&
    process.env.MTN_MOMO_SUBSCRIPTION_KEY
  );
}

/* ── Token Cache ───────────────────────────────────────────── */

let cachedToken: string | null = null;
let tokenExpiresAt = 0;

/**
 * Get a valid OAuth 2.0 Bearer token.
 * Tokens last 3600s — we refresh 60s before expiry.
 */
async function getToken(): Promise<string> {
  const now = Date.now();

  if (cachedToken && now < tokenExpiresAt) {
    return cachedToken;
  }

  const config = getConfig();
  const basicAuth = Buffer.from(
    `${config.apiUserId}:${config.apiKey}`
  ).toString("base64");

  const res = await fetch(`${config.baseUrl}/collection/token/`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${basicAuth}`,
      "Ocp-Apim-Subscription-Key": config.subscriptionKey,
    },
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`MTN token request failed (${res.status}): ${body}`);
  }

  const data = await res.json();
  cachedToken = data.access_token;
  // Refresh 60 seconds before actual expiry
  tokenExpiresAt = now + (data.expires_in - 60) * 1000;

  return cachedToken!;
}

/* ── Request to Pay ────────────────────────────────────────── */

export interface RequestToPayParams {
  /** Unique UUID for this transaction (generated by caller) */
  referenceId: string;
  /** Amount in ZMW as string */
  amount: string;
  /** MSISDN in international format e.g. "260971234567" */
  msisdn: string;
  /** External transaction ID (our tx_ref) */
  externalId: string;
  /** Message shown to the payer */
  payerMessage: string;
  /** Note for the payee (us) */
  payeeNote: string;
}

export interface RequestToPayResult {
  success: boolean;
  referenceId: string;
  error?: string;
}

/**
 * Initiate a Request to Pay.
 * This sends a USSD push to the customer's phone.
 * Returns 202 Accepted — actual result comes via callback or polling.
 */
export async function requestToPay(
  params: RequestToPayParams
): Promise<RequestToPayResult> {
  const config = getConfig();
  const token = await getToken();

  const body = {
    amount: params.amount,
    currency: config.currency,
    externalId: params.externalId,
    payer: {
      partyIdType: "MSISDN",
      partyId: params.msisdn,
    },
    payerMessage: params.payerMessage,
    payeeNote: params.payeeNote,
  };

  const res = await fetch(
    `${config.baseUrl}/collection/v1_0/requesttopay`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "X-Reference-Id": params.referenceId,
        "X-Target-Environment": config.targetEnvironment,
        "Ocp-Apim-Subscription-Key": config.subscriptionKey,
        "X-Callback-Url": config.callbackUrl,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    }
  );

  if (res.status === 202) {
    return { success: true, referenceId: params.referenceId };
  }

  // Error
  const errBody = await res.text();
  console.error(`MTN requestToPay failed (${res.status}):`, errBody);
  return {
    success: false,
    referenceId: params.referenceId,
    error: `MTN API error (${res.status}): ${errBody}`,
  };
}

/* ── Transaction Status ────────────────────────────────────── */

export type MtnTransactionStatus =
  | "PENDING"
  | "SUCCESSFUL"
  | "FAILED"
  | "REJECTED"
  | "TIMEOUT"
  | "ONGOING";

export interface TransactionStatus {
  referenceId: string;
  status: MtnTransactionStatus;
  amount?: string;
  currency?: string;
  financialTransactionId?: string;
  reason?: string;
}

/**
 * Check the status of a Request to Pay transaction.
 */
export async function getTransactionStatus(
  referenceId: string
): Promise<TransactionStatus> {
  const config = getConfig();
  const token = await getToken();

  const res = await fetch(
    `${config.baseUrl}/collection/v1_0/requesttopay/${referenceId}`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "X-Target-Environment": config.targetEnvironment,
        "Ocp-Apim-Subscription-Key": config.subscriptionKey,
      },
    }
  );

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(
      `MTN status check failed (${res.status}): ${errBody}`
    );
  }

  const data = await res.json();
  return {
    referenceId,
    status: data.status,
    amount: data.amount,
    currency: data.currency,
    financialTransactionId: data.financialTransactionId,
    reason: data.reason?.message,
  };
}
