// =============================================================================
// DMSuite — Zambian Legal Reference
// =============================================================================
// Comprehensive reference of Zambian legislation relevant to contracts,
// agreements, and legal documents generated by the platform.
//
// SOURCES:
// 1. National Assembly of Zambia — https://www.parliament.gov.zm/
//    Laws of Zambia (Acts of Parliament) — https://www.parliament.gov.zm/acts/volumes
// 2. Zambia Legal Information Institute (ZambiaLII) — https://zambialii.org/
//    Legislation Index — https://zambialii.org/legislation/act
//    Cross-referenced with court judgments through March 2026
//
// This file is the SINGLE SOURCE OF TRUTH for Zambian legal citations.
// All contract templates, AI prompts, and legal documents reference this file.
// =============================================================================

// ---------------------------------------------------------------------------
// Key Zambian Legislation Index
// ---------------------------------------------------------------------------

export interface ZambianAct {
  /** Short name for display */
  name: string;
  /** Full legal citation */
  citation: string;
  /** Chapter number in Laws of Zambia (if cap-numbered) */
  chapter?: string;
  /** Act number and year (for newer acts) */
  actNumber?: string;
  /** Relevance to contracts */
  relevance: string;
  /** Key provisions */
  keyProvisions: string[];
  /** Contract types this law applies to */
  applicableContractTypes: string[];
}

export const ZAMBIAN_LEGISLATION: ZambianAct[] = [
  // ==============================
  // CONSTITUTIONAL LAW
  // ==============================
  {
    name: "Constitution of Zambia",
    citation: "Constitution of Zambia (Amendment) Act, 2016",
    actNumber: "Act No. 2 of 2016",
    relevance: "Supreme law — all contracts must conform. Fundamental rights including right to property (Art. 16), right to work (Art. 24), freedom of expression (Art. 20), protection from discrimination (Art. 23).",
    keyProvisions: [
      "Article 1: Zambia is a sovereign Republic",
      "Article 11: Fundamental rights and freedoms",
      "Article 16: Protection of right to property",
      "Article 23: Protection from discrimination",
      "Article 24: Protection from deprivation of property without compensation",
      "Part IX: Land and environment provisions",
    ],
    applicableContractTypes: ["all"],
  },

  // ==============================
  // EMPLOYMENT & LABOUR LAW
  // ==============================
  {
    name: "Employment Code Act, 2019",
    citation: "Employment Code Act, 2019 (No. 3 of 2019)",
    actNumber: "Act No. 3 of 2019",
    relevance: "Primary statute governing employment contracts. REPLACES the former Employment Act (Cap. 268) and the Employment of Young Persons and Children Act. Mandates written contracts, sets minimum conditions for wages, hours, leave, termination, severance, and gratuity. Confirmed in active court judgments through 2024 (ZambiaLII).",
    keyProvisions: [
      "Section 24: Written contract of employment required",
      "Section 25: Prohibition of child labour",
      "Section 27: Probationary period — assessment required before confirmation or termination",
      "Section 39: Maximum working hours — 48 hours per week",
      "Section 40: Overtime — not exceeding 48 hours in a 4-week period, paid at 1.5x normal rate",
      "Section 42: Annual leave — minimum 24 working days per year",
      "Section 44: Sick leave — up to 26 working days with full pay",
      "Section 46: Maternity leave — 14 weeks (first 7 weeks at full pay)",
      "Section 47: Paternity leave — minimum 5 working days",
      "Section 52: Termination — must give valid reasons (confirmed by court judgments)",
      "Section 53: Notice of termination — 1 month for monthly-paid, 14 days for fortnightly, 1 pay period otherwise; or payment in lieu",
      "Section 54: Severance pay — 25% of basic pay for each completed year of service",
      "Section 55: Redundancy — consultation and fair selection required",
      "Section 73: Gratuity — mandatory for contracts of 2 or more years",
    ],
    applicableContractTypes: ["employment-contract"],
  },
  {
    name: "Industrial and Labour Relations Act",
    citation: "Industrial and Labour Relations Act, Chapter 269 of the Laws of Zambia",
    chapter: "Cap. 269",
    relevance: "Governs collective bargaining, trade unions, and the Industrial Relations Court. Employment disputes that cannot be resolved through conciliation may be referred to the Industrial Relations Court.",
    keyProvisions: [
      "Part V: Industrial Relations Court — jurisdiction over employment disputes",
      "Part IV: Collective agreements",
      "Section 85: Unfair labour practices",
      "Section 108: Referral of disputes to Industrial Relations Court",
    ],
    applicableContractTypes: ["employment-contract"],
  },
  {
    name: "Minimum Wages and Conditions of Employment Act",
    citation: "Minimum Wages and Conditions of Employment Act, Chapter 276",
    chapter: "Cap. 276",
    relevance: "Establishes statutory minimum wages. The Minister may set minimum wages for various sectors/categories. All employment contracts must comply with gazetted minimum wages.",
    keyProvisions: [
      "Section 3: Minister may fix minimum wages",
      "Section 4: Minimum wages binding on all employers in specified category",
      "Section 5: Penalties for non-compliance",
      "Statutory Instrument: Minimum Wages Statutory Orders (regularly updated)",
    ],
    applicableContractTypes: ["employment-contract"],
  },
  {
    name: "Occupational Health and Safety Act, 2025",
    citation: "Occupational Health and Safety Act, No. 16 of 2025",
    actNumber: "Act No. 16 of 2025",
    relevance: "Employer obligations for workplace safety. Replaces previous Factories Act. Requires risk assessments, safety equipment, and reporting.",
    keyProvisions: [
      "Employer duty to provide safe working environment",
      "Risk assessment requirements",
      "Provision of personal protective equipment (PPE)",
      "Incident reporting and record-keeping",
      "Workers' right to refuse dangerous work",
    ],
    applicableContractTypes: ["employment-contract", "construction-contract"],
  },
  {
    name: "Workers' Compensation Act",
    citation: "Workers' Compensation Act, Chapter 271",
    chapter: "Cap. 271",
    relevance: "Compensation for work-related injuries and diseases. Employers must contribute to the Workers' Compensation Fund.",
    keyProvisions: [
      "Mandatory employer registration and contributions",
      "Compensation for injury, disability, and death",
      "Schedule of occupational diseases",
    ],
    applicableContractTypes: ["employment-contract", "construction-contract"],
  },
  {
    name: "National Pension Scheme Authority Act",
    citation: "National Pension Scheme Authority Act, No. 40 of 1996",
    actNumber: "Act No. 40 of 1996",
    relevance: "Mandatory pension contributions. Employer contributes 5% of gross earnings and employee contributes 5% (total 10%). All employment contracts must reference NAPSA compliance.",
    keyProvisions: [
      "Section 15: Mandatory membership",
      "Section 16: Contribution rates — 5% employer, 5% employee",
      "Section 17: Monthly contribution deadlines",
      "Section 26: Penalties for late/non-payment",
    ],
    applicableContractTypes: ["employment-contract"],
  },

  // ==============================
  // PROPERTY & TENANCY LAW
  // ==============================
  {
    name: "Landlord and Tenant (Business Premises) Act",
    citation: "Landlord and Tenant (Business Premises) Act, Chapter 190",
    chapter: "Cap. 190",
    relevance: "Governs business tenancies. Provides security of tenure for business tenants. Regulates rent reviews, renewals, and termination of business leases.",
    keyProvisions: [
      "Section 3: Application to business premises",
      "Section 5: Security of tenure for business tenants",
      "Section 7: Tenant's right to request new tenancy",
      "Section 9: Grounds for opposing renewal",
      "Section 12: Compensation for failure to renew",
      "Section 14: Rent determination procedures",
    ],
    applicableContractTypes: ["lease-agreement", "tenancy-agreement"],
  },
  {
    name: "Rent Act",
    citation: "Rent Act, Chapter 206 of the Laws of Zambia",
    chapter: "Cap. 206",
    relevance: "Controls residential rents and provides tenant protections. Regulates eviction procedures. Applies to controlled tenancies and dwelling houses.",
    keyProvisions: [
      "Section 2: Definitions — controlled tenancy, dwelling house",
      "Section 3: Application to controlled premises",
      "Section 8: Rent restrictions on controlled premises",
      "Section 12: Prohibition on premiums",
      "Section 14: Notice to quit requirements (minimum 1 month)",
      "Section 15: Court order required for eviction",
      "Section 16: Grounds for possession",
      "Section 18: Protection from retaliatory eviction",
      "Section 20: Tenant's right to essential services",
    ],
    applicableContractTypes: ["tenancy-agreement", "lease-agreement"],
  },
  {
    name: "Lands Act",
    citation: "Lands Act, No. 29 of 1995",
    actNumber: "Act No. 29 of 1995",
    relevance: "Vests all land in Zambia in the President on behalf of the people. Governs grant of leasehold (99 years max). All land transactions must comply. Customary land conversion to leasehold.",
    keyProvisions: [
      "Section 3: All land vested in the President",
      "Section 4: Alienation of land on State Land",
      "Section 5: Leasehold not exceeding 99 years",
      "Section 7: Restrictions on land held by non-Zambians",
      "Section 8: President's consent for alienation/transfer",
      "Section 10: Customary land provisions",
    ],
    applicableContractTypes: ["property-sale-agreement", "lease-agreement", "tenancy-agreement"],
  },
  {
    name: "Lands and Deeds Registry Act",
    citation: "Lands and Deeds Registry Act, Chapter 185",
    chapter: "Cap. 185",
    relevance: "Requires registration of all dealings in land. Property transfers/leases must be registered. Unregistered interests are void against subsequent registered purchasers.",
    keyProvisions: [
      "Section 4: Registrar of Lands and Deeds",
      "Section 33: Registration of instruments",
      "Section 34: Priority based on date of registration",
      "Section 38: Mandatory registration for validity against third parties",
      "Section 42: Assignment and subletting require registration",
    ],
    applicableContractTypes: ["property-sale-agreement", "lease-agreement", "tenancy-agreement"],
  },
  {
    name: "Property Transfer Tax Act",
    citation: "Property Transfer Tax Act, Chapter 340 (as amended 2024, 2025)",
    chapter: "Cap. 340",
    actNumber: "Amended by Act No. 27 of 2024 and Act No. 21 of 2025",
    relevance: "Imposes tax on transfer of property (land, shares, intellectual property, mining rights). Current rate: 5% of realised value.",
    keyProvisions: [
      "Section 3: Charge to property transfer tax",
      "Tax rate: 5% of realised value (as amended)",
      "Section 5: Exemptions",
      "Section 6: Returns and payment requirements",
      "Section 12: Penalties for non-compliance",
    ],
    applicableContractTypes: ["property-sale-agreement", "shareholders-agreement", "motor-vehicle-sale"],
  },
  {
    name: "Lands Acquisition Act",
    citation: "Lands Acquisition Act, Chapter 296",
    chapter: "Cap. 296",
    relevance: "Governs compulsory acquisition of land by the State. Provides for compensation to landowners.",
    keyProvisions: [
      "Section 3: Power of President to acquire land compulsorily",
      "Section 10: Compensation provisions",
      "Section 12: Disputes referred to Lands Tribunal",
    ],
    applicableContractTypes: ["property-sale-agreement"],
  },
  {
    name: "Lands Tribunal Act",
    citation: "Lands Tribunal Act, Chapter 228 (as amended 2024)",
    chapter: "Cap. 228",
    actNumber: "Amended by Act No. 7 of 2024",
    relevance: "Establishes the Lands Tribunal for resolving land disputes, including disputes between landlords and tenants.",
    keyProvisions: [
      "Jurisdiction over land disputes",
      "Appeal from Lands Tribunal to High Court",
    ],
    applicableContractTypes: ["property-sale-agreement", "lease-agreement", "tenancy-agreement"],
  },

  // ==============================
  // COMMERCIAL & CONTRACT LAW
  // ==============================
  {
    name: "Sale of Goods Act",
    citation: "Sale of Goods Act, Chapter 388 of the Laws of Zambia",
    chapter: "Cap. 388",
    relevance: "Governs sale of goods contracts. Implied terms: satisfactory quality, fitness for purpose, description, title. Buyer's right to reject defective goods.",
    keyProvisions: [
      "Section 12: Implied condition as to title",
      "Section 13: Sale by description",
      "Section 14: Implied condition of satisfactory quality",
      "Section 15: Implied condition of fitness for purpose",
      "Section 20: Transfer of risk with property",
      "Section 34: Buyer's right to examine goods",
      "Section 35: Acceptance of goods",
      "Section 51: Damages for non-delivery",
      "Section 53: Damages for breach of warranty",
    ],
    applicableContractTypes: ["sales-agreement", "supply-agreement"],
  },
  {
    name: "Companies Act",
    citation: "Companies Act, No. 10 of 2017 (as amended 2025)",
    actNumber: "Act No. 10 of 2017; amended by Act No. 23 of 2025",
    relevance: "Governs company formation, directors' duties, shareholder rights, and corporate governance. Essential for shareholder agreements and partnership agreements where companies are involved.",
    keyProvisions: [
      "Part III: Incorporation and registration",
      "Part V: Share capital and shares",
      "Part VII: Directors and officers — duties, liabilities",
      "Part VIII: Shareholder meetings and resolutions",
      "Part IX: Financial statements and audit",
      "Part XII: Winding up and dissolution",
      "Section 76: Directors' duty of care and diligence",
      "Section 77: Directors' duty to avoid conflicts of interest",
    ],
    applicableContractTypes: ["shareholders-agreement", "partnership-agreement"],
  },
  {
    name: "Registration of Business Names Act",
    citation: "Registration of Business Names Act, Chapter 389 (as amended 2025)",
    chapter: "Cap. 389",
    actNumber: "Amended by Act No. 24 of 2025",
    relevance: "Requires registration of business names for sole proprietors and partnerships.",
    keyProvisions: [
      "Mandatory registration for firms and individuals trading under business name",
      "Penalties for non-registration",
    ],
    applicableContractTypes: ["partnership-agreement", "freelance-agreement"],
  },
  {
    name: "Competition and Consumer Protection Act",
    citation: "Competition and Consumer Protection Act, No. 24 of 2010 (as amended 2023)",
    actNumber: "Act No. 24 of 2010; amended by Act No. 21 of 2023",
    relevance: "Prohibits anti-competitive agreements, abuse of dominant position, and unfair trade practices. Consumer protection provisions for goods and services. Non-compete clauses must be reasonable.",
    keyProvisions: [
      "Part IV: Anti-competitive agreements",
      "Part V: Abuse of dominant position",
      "Part VII: Consumer protection",
      "Section 46: Unconscionable conduct",
      "Section 47: Misleading and deceptive conduct",
      "Section 50: Product safety standards",
    ],
    applicableContractTypes: ["sales-agreement", "supply-agreement", "service-agreement", "consulting-agreement"],
  },
  {
    name: "Arbitration Act",
    citation: "Arbitration Act, Chapter 40 of the Laws of Zambia",
    chapter: "Cap. 40",
    relevance: "Governs arbitration proceedings in Zambia. Provides framework for arbitration clauses in contracts. Arbitral awards are enforceable as court judgments.",
    keyProvisions: [
      "Section 6: Validity of arbitration agreements",
      "Section 7: Stay of court proceedings where agreement exists",
      "Section 12: Appointment of arbitrator",
      "Section 17: Award — form and effect",
      "Section 20: Enforcement of awards",
    ],
    applicableContractTypes: ["all"],
  },
  {
    name: "Electronic Communications and Transactions Act",
    citation: "Electronic Communications and Transactions Act, No. 4 of 2021",
    actNumber: "Act No. 4 of 2021",
    relevance: "Recognises electronic signatures and contracts. Establishes legal framework for electronic commerce in Zambia.",
    keyProvisions: [
      "Section 13: Legal recognition of electronic records",
      "Section 14: Validity of electronic signatures",
      "Section 15: Electronic contracts are valid and enforceable",
      "Section 17: Electronic records admissible as evidence",
    ],
    applicableContractTypes: ["all"],
  },
  {
    name: "Investment, Trade and Business Development Act",
    citation: "Investment, Trade and Business Development Act, No. 14 of 2022 (as amended 2024)",
    actNumber: "Act No. 14 of 2022; amended by Act No. 3 of 2024",
    relevance: "Governs foreign and local investment. Provides investment protections and guarantees. Relevant for joint ventures and foreign-owned businesses.",
    keyProvisions: [
      "Part III: Investment protection and guarantee",
      "Part IV: Investor rights and obligations",
      "Section 18: Protection from expropriation",
      "Section 19: Transfer of funds guarantee",
    ],
    applicableContractTypes: ["partnership-agreement", "shareholders-agreement", "mou"],
  },

  // ==============================
  // INTELLECTUAL PROPERTY
  // ==============================
  {
    name: "Trade Marks Act",
    citation: "Trade Marks Act, No. 11 of 2023",
    actNumber: "Act No. 11 of 2023",
    relevance: "Registration and protection of trade marks in Zambia. Relevant for IP clauses in service/consulting/freelance agreements.",
    keyProvisions: [
      "Part III: Registration of trade marks",
      "Part V: Infringement",
      "Part VI: Licensing and assignment",
    ],
    applicableContractTypes: ["service-agreement", "consulting-agreement", "freelance-agreement", "nda"],
  },
  {
    name: "Copyright and Performance Rights Act",
    citation: "Copyright and Performance Rights Act, Chapter 406",
    chapter: "Cap. 406",
    relevance: "Protects copyright in literary, artistic, musical works. Relevant for IP ownership clauses in creative agreements.",
    keyProvisions: [
      "Section 4: Works eligible for copyright",
      "Section 5: Ownership of copyright",
      "Section 7: Economic rights",
      "Section 9: Moral rights",
      "Section 22: Assignment of copyright must be in writing",
    ],
    applicableContractTypes: ["freelance-agreement", "consulting-agreement", "service-agreement"],
  },
  {
    name: "Patents Act",
    citation: "Patents Act, Chapter 400",
    chapter: "Cap. 400",
    relevance: "Patent protection. Relevant for IP clauses especially in technology and innovation contracts.",
    keyProvisions: [
      "Section 3: Patentable inventions",
      "Section 17: Rights of patent holder",
      "Section 22: Assignment and licensing",
    ],
    applicableContractTypes: ["service-agreement", "consulting-agreement", "nda"],
  },

  // ==============================
  // TAX LAW
  // ==============================
  {
    name: "Income Tax Act",
    citation: "Income Tax Act, Chapter 323 (as amended 2024, 2025)",
    chapter: "Cap. 323",
    relevance: "All contract payments are subject to income tax. Withholding tax on payments to contractors (15%). PAYE for employment income.",
    keyProvisions: [
      "Section 11: Charge to income tax",
      "Part IV: Deductions and exemptions",
      "Section 82: PAYE — Pay As You Earn system",
      "Section 82A: Withholding tax on contract payments (15%)",
      "Section 83: Filing requirements",
    ],
    applicableContractTypes: ["employment-contract", "freelance-agreement", "service-agreement", "consulting-agreement"],
  },
  {
    name: "Value Added Tax Act",
    citation: "Value Added Tax Act, Chapter 331 (as amended 2023, 2024, 2025)",
    chapter: "Cap. 331",
    relevance: "VAT at standard rate (16%) on taxable supplies. Businesses with turnover above threshold must register. All commercial contracts should address VAT treatment.",
    keyProvisions: [
      "Section 7: Standard rate of 16%",
      "Section 8: Zero-rated supplies (Schedule 1)",
      "Section 9: Exempt supplies (Schedule 2)",
      "Section 10: Registration threshold",
      "Section 22: Tax invoices required",
    ],
    applicableContractTypes: ["service-agreement", "sales-agreement", "supply-agreement", "consulting-agreement", "construction-contract"],
  },

  // ==============================
  // CONSTRUCTION & PUBLIC WORKS
  // ==============================
  {
    name: "National Council for Construction Act",
    citation: "National Council for Construction Act, No. 13 of 2003 (as amended by Act No. 10 of 2020)",
    actNumber: "Act No. 13 of 2003; amended by Act No. 10 of 2020",
    relevance: "Governs registration of contractors and construction industry regulation. Contractors must be registered with NCC.",
    keyProvisions: [
      "Section 24: Registration of contractors mandatory",
      "Section 25: Contractor grades and categories",
      "Section 32: Penalties for unregistered contractors",
    ],
    applicableContractTypes: ["construction-contract"],
  },
  {
    name: "Public-Private Partnership Act",
    citation: "Public-Private Partnership Act, No. 18 of 2023",
    actNumber: "Act No. 18 of 2023",
    relevance: "Framework for PPP arrangements between government and private sector.",
    keyProvisions: [
      "Part III: PPP approval process",
      "Part IV: PPP agreement requirements",
      "Part V: Monitoring and evaluation",
    ],
    applicableContractTypes: ["construction-contract", "mou"],
  },

  // ==============================
  // FAMILY & MATRIMONIAL LAW
  // ==============================
  {
    name: "Marriage Act",
    citation: "Marriage Act, Chapter 50 (as amended by Act No. 13 of 2023)",
    chapter: "Cap. 50",
    relevance: "Governs statutory marriages. Relevant for property agreements between spouses.",
    keyProvisions: [
      "Section 14: Conditions for valid marriage",
      "Section 33: Effect of marriage on property",
      "2023 Amendment: Minimum age raised to 21 for both parties",
    ],
    applicableContractTypes: ["property-sale-agreement"],
  },
  {
    name: "Matrimonial Causes Act",
    citation: "Matrimonial Causes Act, Chapter 57 (as amended by Act No. 6 of 2024)",
    chapter: "Cap. 57",
    relevance: "Governs division of matrimonial property. Relevant for property and business agreements involving married parties.",
    keyProvisions: [
      "Section 34: Court power to divide property on divorce",
      "Section 35: Orders regarding tenancy of matrimonial home",
      "2024 Amendment: Enhanced provisions for equitable division",
    ],
    applicableContractTypes: ["property-sale-agreement", "tenancy-agreement"],
  },

  // ==============================
  // DISPUTE RESOLUTION
  // ==============================
  {
    name: "Small Claims Courts Act",
    citation: "Small Claims Courts Act, No. 28 of 1992 (as amended by Act No. 15 of 2025)",
    chapter: "Cap. 47",
    actNumber: "Amended by Act No. 15 of 2025",
    relevance: "Simplified court procedure for smaller claims. Relevant for consumer and small business disputes.",
    keyProvisions: [
      "Simplified procedure without lawyers",
      "Jurisdiction over civil matters below statutory threshold",
      "2025 Amendment: Increased jurisdictional amounts",
    ],
    applicableContractTypes: ["sales-agreement", "service-agreement"],
  },
  {
    name: "High Court Act",
    citation: "High Court Act, Chapter 27",
    chapter: "Cap. 27",
    relevance: "Unlimited jurisdiction for civil claims. Contract disputes above subordinate court limits are heard in the High Court.",
    keyProvisions: [
      "Section 11: Unlimited original jurisdiction in civil cases",
      "Section 14: Appeals from subordinate courts",
    ],
    applicableContractTypes: ["all"],
  },

  // ==============================
  // MOTOR VEHICLES
  // ==============================
  {
    name: "Road Traffic Act",
    citation: "Road Traffic Act, No. 11 of 2002",
    actNumber: "Act No. 11 of 2002",
    relevance: "Governs vehicle registration and transfer. Road Transport and Safety Agency (RTSA) administers vehicle registration. Vehicle transfers must be registered with RTSA.",
    keyProvisions: [
      "Section 7: RTSA establishment and powers",
      "Section 24: Registration of motor vehicles",
      "Section 25: Transfer of registration (notification within 14 days)",
      "Section 28: Certificate of fitness requirements",
      "Section 66: Road tax requirements",
    ],
    applicableContractTypes: ["motor-vehicle-sale"],
  },

  // ==============================
  // DATA PROTECTION & ELECTRONIC TRANSACTIONS
  // ==============================
  {
    name: "Data Protection Act, 2021",
    citation: "Data Protection Act, 2021 (No. 3 of 2021)",
    actNumber: "Act No. 3 of 2021",
    relevance: "Regulates collection, processing, storage, and sharing of personal data. All contracts involving personal data must comply. Relevant for NDAs, employment contracts, and any agreement handling personal information.",
    keyProvisions: [
      "Section 25: Principles of lawful data processing",
      "Section 27: Duty to inform data subjects",
      "Section 30: Data subject rights (access, correction, deletion)",
      "Section 43: Cross-border transfer restrictions",
      "Section 57: Penalties for unlawful processing",
    ],
    applicableContractTypes: ["nda", "employment-contract", "consulting-agreement", "service-agreement", "freelance-agreement"],
  },

  // ==============================
  // ADDITIONAL CONTRACT LAW
  // ==============================
  {
    name: "Misrepresentation Act",
    citation: "Misrepresentation Act, Chapter 69 of the Laws of Zambia",
    chapter: "Cap. 69",
    relevance: "Provides remedies for misrepresentation inducing a party to enter into a contract. Relevant to all contract types — a contract may be rescinded if entered into based on misrepresentation.",
    keyProvisions: [
      "Section 2: Remedies for misrepresentation",
      "Section 3: Damages in lieu of rescission",
    ],
    applicableContractTypes: ["all"],
  },
  {
    name: "Law Reform (Frustrated Contracts) Act",
    citation: "Law Reform (Frustrated Contracts) Act, Chapter 73 of the Laws of Zambia",
    chapter: "Cap. 73",
    relevance: "Governs the consequences of frustration of contract (impossibility of performance). Relevant for force majeure clauses and pandemic-related provisions.",
    keyProvisions: [
      "Section 2: Recovery of sums paid before frustrating event",
      "Section 3: Assessment of valuable benefit obtained",
    ],
    applicableContractTypes: ["all"],
  },
  {
    name: "Hire Purchase Act",
    citation: "Hire Purchase Act, 1956 (Act No. 34X of 1956)",
    chapter: "Cap. 399",
    relevance: "Governs hire purchase (installment) agreements for goods. Relevant for motor vehicle and goods sales on installment terms.",
    keyProvisions: [
      "Section 3: Hire purchase agreements must be in writing",
      "Section 5: Hirer's rights and obligations",
      "Section 10: Owner's right to recover goods",
    ],
    applicableContractTypes: ["motor-vehicle-sale", "sales-agreement"],
  },
  {
    name: "Credit Reporting Act, 2018",
    citation: "Credit Reporting Act, 2018 (No. 8 of 2018)",
    actNumber: "Act No. 8 of 2018",
    relevance: "Regulates credit information sharing and reporting. Relevant for loan agreements and any credit-based transactions.",
    keyProvisions: [
      "Section 16: Borrower consent for credit checks",
      "Section 22: Right to dispute credit information",
    ],
    applicableContractTypes: ["loan-agreement"],
  },
  {
    name: "Movable Property (Security Interests) Act, 2016",
    citation: "Movable Property (Security Interests) Act, 2016 (No. 3 of 2016)",
    actNumber: "Act No. 3 of 2016",
    relevance: "Governs security interests in movable property. Provides framework for registering pledges and charges over movable assets as loan security.",
    keyProvisions: [
      "Section 6: Creation of security interest",
      "Section 10: Registration at collateral registry",
      "Section 24: Priority rules",
    ],
    applicableContractTypes: ["loan-agreement"],
  },
  {
    name: "Estate Agents Act, 2000",
    citation: "Estate Agents Act, 2000 (No. 21 of 2000)",
    actNumber: "Act No. 21 of 2000",
    relevance: "Regulates estate agents and property brokers. Relevant for property sale agreements where agents are involved.",
    keyProvisions: [
      "Section 5: Registration of estate agents",
      "Section 12: Commission and fee regulations",
    ],
    applicableContractTypes: ["property-sale-agreement"],
  },
];

// ---------------------------------------------------------------------------
// Helper: Get legislation applicable to a contract type
// ---------------------------------------------------------------------------

export function getLegislationForContractType(contractType: string): ZambianAct[] {
  return ZAMBIAN_LEGISLATION.filter(
    (act) =>
      act.applicableContractTypes.includes("all") ||
      act.applicableContractTypes.includes(contractType),
  );
}

// ---------------------------------------------------------------------------
// Helper: Get a formatted legal citation string for documents
// ---------------------------------------------------------------------------

export function getGoverningLawText(): string {
  return "This Agreement shall be governed by and construed in accordance with the Laws of the Republic of Zambia, including but not limited to the Constitution of Zambia (Amendment) Act, 2016, and all subsidiary legislation applicable thereto.";
}

export function getDisputeResolutionText(includeArbitration: boolean = false): string {
  if (includeArbitration) {
    return (
      "Any dispute, difference, or question arising out of or in connection with this Agreement shall first be resolved through good-faith negotiation between the parties. " +
      "If negotiation fails within thirty (30) days, the dispute shall be referred to mediation administered by a mutually agreed mediator. " +
      "If mediation is unsuccessful within a further thirty (30) days, the dispute shall be submitted to binding arbitration in accordance with the Arbitration Act, Chapter 40 of the Laws of Zambia. " +
      "The arbitration shall be conducted in Lusaka by a sole arbitrator appointed by agreement of the parties, or failing agreement within fourteen (14) days, by the President of the Law Association of Zambia. " +
      "The arbitral award shall be final and binding on both parties."
    );
  }
  return (
    "Any dispute arising from or in connection with this Agreement shall first be resolved through good-faith negotiation between the parties. " +
    "If negotiation fails within thirty (30) days, the dispute shall be referred to mediation. " +
    "If mediation is unsuccessful, the dispute shall be submitted to the exclusive jurisdiction of the courts of Lusaka, Republic of Zambia."
  );
}

// ---------------------------------------------------------------------------
// Zambia-Specific Legal Formalities
// ---------------------------------------------------------------------------
export const ZAMBIA_LEGAL_NOTES = {
  currency: "Zambian Kwacha (ZMW)",
  vatRate: "16% (standard rate)",
  withholdingTax: "15% on payments to contractors and consultants",
  paye: "Progressive tax rates applied via PAYE system",
  napsa: "10% of gross salary (5% employer, 5% employee)",
  minNoticeEmployment: "1 month for monthly-paid employees, 14 days for fortnightly-paid, 1 pay period otherwise (Section 53, Employment Code Act 2019)",
  severancePay: "25% of basic pay for each completed year of service (Section 54, Employment Code Act 2019)",
  gratuity: "Mandatory for contracts of 2 or more years (Section 73, Employment Code Act 2019)",
  maxLeasehold: "99 years (all land vested in President)",
  propertyTransferTax: "5% of realised value",
  witnessRequirements: "At least one (1) independent witness required for signature. NRC/Passport number of witness should be recorded.",
  sealRequirements: "Companies should affix company seal where required by their Articles of Incorporation.",
  stampDuty: "Applicable on certain documents as per Stamp Duty Act, Cap. 339. Unstamped documents may not be admitted as evidence.",
  notarisation: "Documents for use in foreign jurisdictions may need notarisation by a Zambian Notary Public.",
  nrcRequirement: "National Registration Card (NRC) number should be included for all individual parties as identification.",
  tpin: "Tax Payer Identification Number (TPIN) — all business entities must include their TPIN issued by ZRA.",
  rtsaTransfer: "Motor vehicle transfers must be registered with RTSA within 14 days of sale.",
};

// ---------------------------------------------------------------------------
// Legal Disclaimer (shown on generated documents)
// ---------------------------------------------------------------------------
export const LEGAL_DISCLAIMER =
  "This document was generated using DMSuite — AI-Powered Document Suite. " +
  "While this document has been drafted to comply with the Laws of the Republic of Zambia, " +
  "it is provided for informational purposes and may require customisation for specific circumstances. " +
  "The parties are advised to seek independent legal counsel before executing this Agreement. " +
  "DMSuite and Dramac Agency shall not be liable for any loss or damage arising from the use of this document.";

// ---------------------------------------------------------------------------
// Key Sources & URLs
// ---------------------------------------------------------------------------
export const LEGAL_SOURCES = {
  parliament: "https://www.parliament.gov.zm/",
  actsOfParliament: "https://www.parliament.gov.zm/acts-of-parliament/",
  lawsOfZambia: "https://www.parliament.gov.zm/acts/volumes",
  govAgreements: "https://www.parliament.gov.zm/agreements/gov_agreements",
  bills: "https://www.parliament.gov.zm/publications/bills-list/",
};
