/* ═══════════════════════════════════════════════════════════════════════════
 * DMSuite — Presentation Designer: Theme Presets
 *
 * 8 professional themes with gradient backgrounds, complementary palettes,
 * decorative accents, and font pairings.
 * ═══════════════════════════════════════════════════════════════════════════ */

import type { PresentationTheme } from "./types";

export const PRESENTATION_THEMES: PresentationTheme[] = [
  // ── 1. Midnight ─────────────────────────────
  {
    id: "midnight",
    name: "Midnight",
    bgPrimary: "#0f172a",
    bgSecondary: "#1e293b",
    bgGradient: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #312e81 100%)",
    textPrimary: "#f1f5f9",
    textSecondary: "#94a3b8",
    textOnAccent: "#0f172a",
    accent: "#a5f3fc",
    accentSoft: "rgba(165,243,252,0.15)",
    borderColor: "#334155",
    decorShape: "circles",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 2. Corporate ────────────────────────────
  {
    id: "corporate",
    name: "Corporate",
    bgPrimary: "#ffffff",
    bgSecondary: "#f8fafc",
    bgGradient: "linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%)",
    textPrimary: "#1e293b",
    textSecondary: "#64748b",
    textOnAccent: "#ffffff",
    accent: "#2563eb",
    accentSoft: "rgba(37,99,235,0.08)",
    borderColor: "#e2e8f0",
    decorShape: "lines",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 3. Sunset ───────────────────────────────
  {
    id: "sunset",
    name: "Sunset",
    bgPrimary: "#1c1917",
    bgSecondary: "#292524",
    bgGradient: "linear-gradient(135deg, #7c2d12 0%, #ea580c 40%, #fbbf24 100%)",
    textPrimary: "#fef3c7",
    textSecondary: "#d6d3d1",
    textOnAccent: "#1c1917",
    accent: "#fb923c",
    accentSoft: "rgba(251,146,60,0.15)",
    borderColor: "#44403c",
    decorShape: "waves",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 4. Forest ───────────────────────────────
  {
    id: "forest",
    name: "Forest",
    bgPrimary: "#022c22",
    bgSecondary: "#064e3b",
    bgGradient: "linear-gradient(135deg, #022c22 0%, #065f46 50%, #059669 100%)",
    textPrimary: "#ecfdf5",
    textSecondary: "#a7f3d0",
    textOnAccent: "#022c22",
    accent: "#34d399",
    accentSoft: "rgba(52,211,153,0.15)",
    borderColor: "#047857",
    decorShape: "dots",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 5. Ocean ────────────────────────────────
  {
    id: "ocean",
    name: "Ocean",
    bgPrimary: "#0c4a6e",
    bgSecondary: "#075985",
    bgGradient: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 50%, #38bdf8 100%)",
    textPrimary: "#f0f9ff",
    textSecondary: "#bae6fd",
    textOnAccent: "#0c4a6e",
    accent: "#38bdf8",
    accentSoft: "rgba(56,189,248,0.15)",
    borderColor: "#0369a1",
    decorShape: "waves",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 6. Minimal ──────────────────────────────
  {
    id: "minimal",
    name: "Minimal",
    bgPrimary: "#ffffff",
    bgSecondary: "#fafafa",
    bgGradient: "linear-gradient(135deg, #18181b 0%, #3f3f46 100%)",
    textPrimary: "#18181b",
    textSecondary: "#71717a",
    textOnAccent: "#ffffff",
    accent: "#18181b",
    accentSoft: "rgba(24,24,27,0.06)",
    borderColor: "#e4e4e7",
    decorShape: "none",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 7. Neon ─────────────────────────────────
  {
    id: "neon",
    name: "Neon",
    bgPrimary: "#09090b",
    bgSecondary: "#18181b",
    bgGradient: "linear-gradient(135deg, #09090b 0%, #1e1b4b 50%, #4c1d95 100%)",
    textPrimary: "#fafafa",
    textSecondary: "#a1a1aa",
    textOnAccent: "#09090b",
    accent: "#a78bfa",
    accentSoft: "rgba(167,139,250,0.15)",
    borderColor: "#27272a",
    decorShape: "circles",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  // ── 8. Earth ────────────────────────────────
  {
    id: "earth",
    name: "Earth",
    bgPrimary: "#1c1917",
    bgSecondary: "#292524",
    bgGradient: "linear-gradient(135deg, #451a03 0%, #78350f 50%, #a16207 100%)",
    textPrimary: "#fefce8",
    textSecondary: "#d6d3d1",
    textOnAccent: "#1c1917",
    accent: "#fbbf24",
    accentSoft: "rgba(251,191,36,0.15)",
    borderColor: "#44403c",
    decorShape: "dots",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
];

export const DEFAULT_THEME = PRESENTATION_THEMES[0]; // Midnight
